version: '3.7'

services:
  php:
    image: graphicresources/itpg-api-coding-task:development
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    environment:
      docker: "true"
    ports:
      - "8080:8080"
    volumes:
      - ./app:/var/www
      - ./opt/db/:/var/db
    networks:
      - bridge

  db:
    restart: always
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./opt/db:/docker-entrypoint-initdb.d
      - ./config/mariadb/my.conf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lotr
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES; \""
      interval: 3s
      timeout: 1s
      retries: 5
    networks:
      - bridge

networks:
  bridge: