name: PHP Tests

on: [push, pull_request]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker and Make
        run: |
          sudo apt-get update
          sudo apt-get install -y make docker-compose

      - name: Build project
        run: make build

      - name: Build and start Docker containers
        run: docker-compose up -d --build

      - name: Install PHP CodeSniffer and PHPStan
        run: |
          docker-compose exec -T php composer install

      - name: Run PHP UnitTests
        run: docker-compose exec -T php vendor/bin/phpunit --testsuite "Application Test Suite"

      - name: Stop and remove Docker containers
        run: docker-compose down
